"""Review gallery for the four bounded service batches, using native captures."""
import html,json
from tools.rom import ROOT,digest,require

def run():
 out=ROOT/'build/services';build=json.loads((ROOT/'build/english/build.json').read_text());images=[];blocks=[]
 groups=[('Dungeon UI and commands','dungeon-ui',[
  ('controls/status.png','Weapon and status values'),('controls/options.png','Option menu'),('controls/selected.png','Controls help'),('give-up/selected.png','Give up warning')]),
 ('Bank transactions','bank',[('roundtrip/menu.png','Bank labels and balances'),('roundtrip/amount-or-empty.png','Amount editor'),('deposit-overflow-no/warning-first-page.png','Excess-gold warning (controlled balance)'),('roundtrip/deposited.png','Natural deposit')]),
 ('Bank rewards (controlled eligibility and balances)','bank-rewards',[('tier-7/page-03.png','Three-item gift: first two items'),('tier-7/page-04.png','Three-item gift: final item'),('tier-7-widest-Japanese/page-03.png','Gift text with widest supported player name'),('tier-7-full/page-03.png','Full-inventory gift refusal')]),
 ('Bakery transactions (controlled service invocation)','bakery',[('buy-2/menu.png','Original bread-menu geometry and aligned prices'),('buy-2/confirmation.png','Magic bread purchase confirmation'),('buy-again/purchased-again.png','Second purchase confirmation'),('max-name-widest-Japanese/full-first-page.png','Full inventory with widest player name')]),
 ('206 identified item names and their Info text','items',[('natural-0/inventory.png','Naturally carried items'),('natural-2/info.png','Shield description'),('30-maximum-fields/inventory.png','Enhancement limit (controlled)'),('30-priced/inventory.png','Continuous price background (controlled)'),('51-maximum-fields/inventory.png','Lightning staff with maximum charges (controlled)'),('6-priced-equipped-maximum/inventory.png','Compact Liquid metal sword name, enhancement and price'),('135-invisible-visible/info.png','Hocus Pocus scroll description with controlled visibility'),('135-identified/info.png','Native invisible-item fallback'),('38-ability-present/info.png','Ogre shield with native ability bit present'),('59-name-widest-Japanese/info.png','Surefoot staff with widest supported player name'),('18-identified/info.png','Pickaxe description (controlled)')]),
 ('Repaired storage','storage',[('single-roundtrip/menu.png','Original two-column menu'),('single-roundtrip/deposited.png','Deposit confirmation'),('single-roundtrip/withdrawn.png','Withdrawal confirmation'),('batch-deposit/marked.png','Marking all carried items'),('cold-deposit/stored-after-reload.png','Stored items survive cold reload'),('single-roundtrip/empty.png','Empty storage')]),
 ('Storage transactions and limits','storage-services',[('sell-carried-yes/confirmation.png','Carried-item sale confirmation'),('sell-stored-yes/result.png','Stored-item sale result'),('filled-pot-no/confirmation.png','Break-pot confirmation (controlled)'),('full-storage/full.png','Full warehouse (controlled)'),('full-inventory/full.png','Full inventory (controlled)')]),
 ('Sacred-flame quest text (controlled reader)','holy-flame-text',[('event-bank-1.691e-native/page-0.png','Blacksmith dialogue'),('event-bank-1.2b5f-native/page-0.png','Quest dialogue'),('rom.00061998-widest-Japanese/page-0.png','Acquisition with widest supported Japanese name')])] 
 for title,name,rows in groups:
  report=json.loads((ROOT/f'build/english/{name}-validation/report.json').read_text())
  require(report['passed'] and report['rom_sha256']==build['output_sha256'],'Stale service gallery: '+name)
  cards=[]
  for filename,caption in rows:
   path=ROOT/f'build/english/{name}-validation'/filename;rel=str(path.relative_to(ROOT))
   images.append({'source':rel,'caption':caption,'sha256':digest(path.read_bytes())})
   cards.append(f'<figure><figcaption>{html.escape(caption)}</figcaption><img width="480" height="320" src="../../{html.escape(rel)}" alt="{html.escape(caption)}"></figure>')
  blocks.append('<h2>'+html.escape(title)+'</h2><div class="grid">'+''.join(cards)+'</div>')
 (out/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Torneko 2 service batches</title><style>body{background:#12192a;color:white;font:17px/1.5 system-ui;max-width:1100px;margin:30px auto;padding:0 16px}.grid{display:flex;flex-wrap:wrap}figure{margin:10px}img{image-rendering:pixelated;max-width:100%;height:auto}a{color:#9de6d0}</style><h1>Dungeon UI, banking, items and storage</h1><p>Native mGBA screenshots from one cumulative English ROM. Original window sizes, matching compact numbers and three-pixel word spaces. Controlled item/balance cases are labelled separately.</p><p>The repaired warehouse was reached through ordinary play, including the castle quest. Its bread and wand were naturally acquired. Deposit, withdrawal, marking, cancellation and a saved deposit/cold reload were checked. Storage sales and controlled capacity/filled-pot branches now pass. Bank deposits and withdrawals survive native saves and cold reloads. Sacred-flame screenshots use controlled source arguments at the native reader; they do not establish ordinary English quest completion. Bank reward thresholds, gift names, three-item pagination and full-inventory refusal pass controlled native checks. The early checkpoint normally disables rewards; the verifier enables that argument only in its disposable session. All 221 item definitions have translated names. Controlled row checks cover valid identified, equipped, cursed, appearance and price states; item153 has no valid unidentified appearance (native alias999), and inscription/acquisition paths remain separate. Bakery text passes thirteen controlled service cases, including exact prices, all three delivered breads, repeated purchases and refusal branches. Ordinary bakery unlocking and saved purchases remain open, along with inscriptions, acquisition of special item records and later modes. All154 unidentified appearance labels have separate controlled row coverage.</p><p><a href="../typography/index.html">Typography before/after</a> · <a href="../font-audition/index.html">Font and width budgets</a> · <a href="../../docs/SERVICE_BATCHES.md">Batch scope</a></p>'''+''.join(blocks)+'</html>')
 (out/'preview.json').write_text(json.dumps({'rom_sha256':build['output_sha256'],'images':images},indent=2)+'\n');print(out/'index.html')
if __name__=='__main__':run()
